### ISSUE TITLE
'C to °C

### ISSUE THREAD

**Issue by Shorty01** [MichMich/mmm-systemtemperature#1]
Hey Michael,
I think it would be nice, if the apostrophe before 'C could be replaced with the more common (at least where I live) °C .
![c](https://cloud.githubusercontent.com/assets/18481233/14932515/cdd188ce-0e77-11e6-94c7-593dcb3bc5cc.JPG)

This could be easily accomplished by changing `stdout.replace('temp=','')` in the node_helper.js to `stdout.replace('temp=','').replace('\'','\°')`

PS: I'm kinda new to all this (GitHub) and I'll apologize if something will go wrong.

**Comment by MichMich** [comment]
Merged your PR. Thanks!
